# -*- coding: utf-8 -*-
"""NoModulaciones

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16IPV5saknsqqyw_okrG6J67Dr-vTgyQ0
"""

import streamlit as st
import pandas as pd

st.set_page_config(page_title="Analizador de Hojas", layout="wide")

st.title("📂 Cargador de Base de Datos")
st.write("Sube un archivo Excel (.xlsx) o CSV para ver el contenido de sus hojas.")

# Widget para subir el archivo
uploaded_file = st.file_uploader("Elige un archivo", type=['xlsx', 'csv'])

if uploaded_file is not None:
    try:
        # Verificar si es Excel o CSV
        if uploaded_file.name.endswith('.csv'):
            df = pd.read_csv(uploaded_file)
            st.subheader("Contenido del archivo CSV")
            st.dataframe(df.head())

        else:
            # Leer todas las hojas del Excel
            # sheet_name=None carga un diccionario con todas las hojas
            excel_file = pd.ExcelFile(uploaded_file)
            nombres_hojas = excel_file.sheet_names

            st.success(f"Se encontraron {len(nombres_hojas)} hojas: {', '.join(nombres_hojas)}")

            for hoja in nombres_hojas:
                st.markdown(f"---")
                st.subheader(f"📄 Hoja: {hoja}")
                # Leer solo la hoja actual
                df_hoja = pd.read_excel(uploaded_file, sheet_name=hoja)

                if df_hoja.empty:
                    st.warning("Esta hoja está vacía.")
                else:
                    st.write(f"Primeras filas de '{hoja}':")
                    st.dataframe(df_hoja.head()) # Muestra las primeras 5 filas

    except Exception as e:
        st.error(f"Hubo un error al procesar el archivo: {e}")